### ISSUE TITLE
[Enhancement] Release Linux GUI version

### ISSUE THREAD

**Issue by menelic** [graphlab-fr/cosma#21]
### Which part of Cosma is your request about?

- [X] GUI version (Electron-based app)
- [ ] CLI version (command-line tool)
- [ ] cosmograph (records & cosmoscope creation)
- [ ] cosmoscope (exported graph & records)
- [ ] documentation
- [ ] other

### Describe your request:

Pleas release cosma for Linux. It is a great tool and has the potential t facilitate platform and OS agnostic exchange of knowledge graphs once it is available for Linux as well as for Mac and Windows. as you explain [here](https://cosma.graphlab.fr/en/faq/#the-alpha-was-available-for-linux-what-about-version-10), as an Electron app you can deploy to all these OS from one code base.

**Comment by infologie** [comment]
Thanks @menelic. We do plan to release the GUI for Linux as soon as we can test it properly. @Myllaume is working on it.

**Comment by IgnacioHeredia** [comment]
Hi @infologie @Myllaume , any news on this issue?

I'm eager to try it on Linux 🙃. I know there's the CLI version but I don't find it particularly useful for a first contact because I find it harder to explore the full program capabilities and configuration. It can be useful though once you have your workflow dialed, if you want to automatically generate the graph for example.

**Comment by IgnacioHeredia** [comment]
Thanks so much! The app looks very cool indeed, so it will definitely worth the patience. 🚀

**Comment by AntonioBlaGra** [comment]
Anyone was able to run the Windows version with Wine (as a workaround until the Linux version is released)?

**Comment by IgnacioHeredia** [comment]
> Anyone was able to run the Windows version with Wine (as a workaround until the Linux version is released)?

I didn't try, could be an option in the meantime.

**Comment by infologie** [comment]
@menelic @IgnacioHeredia @AntonioBlaGra The GUI version is now available for Linux as an experimental v2-beta version. However, we are planning important changes to Cosma, which includes suspending our work on the GUI. It will remain available via GitHub but we do not plan to provide any support or updates for it. We are going to reorganize our GitHub repos in the coming weeks to reflect this.

More info here: <https://cosma.graphlab.fr/en/roadmap/>

I'm encouraging people to check out some upcoming resources we're working on, including this guide to getting started with the CLI: <https://cosma.arthurperret.fr/getting-started.html>

**Comment by IgnacioHeredia** [comment]
Hi @infologie, 

I just tested the beta and works great! Had a few issues with YAML title naming (no `:` allowed, having `_` leading to bad formatting, etc). But overall the process went quite well, and the end result with CSS customizations looks _gorgeous_.

![Screenshot from 2023-05-15 23-38-16](https://github.com/graphlab-fr/cosma/assets/16413205/fdb98076-f4c3-459e-860a-6c15fd633fc7)

I totally understand that you don't have the time to mantain the GUI. But I wouldn't completely drop support for the GUI, as I found the workflow _much_ smoother than with the CLI (which I also tested, and am confortable using in my day-to-day). Maybe a web version is a good compromise.

Thanks anyway for releasing the Linux version!

**Comment by infologie** [comment]
> I wouldn't completely drop support for the GUI, as I found the workflow much smoother than with the CLI

Of course it's smoother: to get a cosmocope, you just press a button! But this ease of use implies massive work on our end, from design to development and tests, which we just can't afford right now. The GUI and CLI make the same thing, the cosmoscope, and it's there that we want our focus to be.

I admit that the CLI is a little more involved than the GUI, especially regarding the configuration. We're aiming to simplify it in the next update. However, I'll argue that the CLI is just as smooth as the GUI for day-to-day use (e.g. creating records and cosmoscopes), which is what I'm assuming you're talking about when you talk about workflow:

- Creating Markdown files is just as quick with the CLI as with the GUI. `cosma record` is basically a form but in a text interface.
- We provide shorthand versions of commands (`r` for `record`, `m` for `modelize`) and options (`-p` for `--projects`).
- If you use global configurations (with `-p/--projects`), it removes the need to `cd` somewhere. As an example, when I want to update the cosmoscope for my notes, I just open a terminal and run this straight away: `cosma m -p notes`

Now, obviously most people are more comfortable using GUIs. Even CLI enthusiasts such as me: I use a Git client rather than pass `git` commands in the terminal; I write Makefiles and run them with a Cmd+R shortcut in my text editor, rather than with `make` in the terminal.

So I'm aware that we're sacrificing some useability and potentially shutting out some users. This is why we're going to work on simplifying interactions with the CLI, and adding resources to the documentation, such as the [Getting started](https://cosma.arthurperret.fr/getting-started.html) page.

And in the long run:

> Maybe a web version is a good compromise.

This is exactly the plan: replace the GUI with the web version as the most easy to use.

**Comment by IgnacioHeredia** [comment]
@infologie 
I'll argue that in fact, in your day to day, it's easier/faster to use the CLI than the GUI. Once you have all your configuration nicely tuned it's always faster to use the CLI of course. 

What I meant is that the GUI is actually more helpful to _discover_ the software capabilities, to understand what the different element in the configuration mean, etc. But as you said, this initial exploration could be done via a web UI or just spending a bit more time playing with the CLI. 

In any case, thanks so much for making Cosma and I'm looking forward on the progress!
