### ISSUE TITLE
[Bug] Files with a title containing only a date in the "YYYY-MM-DD" format are ignored

### ISSUE THREAD

**Issue by infologie** [graphlab-fr/cosma#33]
### Actions leading to the bug

Create a file with a title containing only a date in the "YYYY-MM-DD" format, e.g. `title: 2020-06-03`.

### Bug description

The corresponding record is not included in the cosmoscope.

### What version of Cosma are you using?

CLI 2.0-beta-1

### What is your operating system?

- [X] macOS
- [ ] Windows
- [ ] Linux

### What version of the operating system are you on?

macOS 12.6.1

### Additional information

Reported by @kevinpolisano.

**Comment by Myllaume** [comment]
`2021-01-01` value is a timestamp, as YAML specification https://yaml.org/type/timestamp.html.
So, Cosma parse a date and not a string.

The question is to know if we respect the specification or if we make an exception.

**Comment by kevinpolisano** [comment]
There are many people who have inserted date in the filename and/or title of their notes (in order to sort and easily retrieved them, see for instance the use of [this guy](https://youtu.be/wB89lJs5A3s?t=4965)). I think personaly that it is not a good (or useful) practise—I prefer to use a 'date' field or the 'id' field containing creation date)—but since it is a common one, I think it would be indeed necessary to catch this exception for the 'title' YAML field. 

PS: special symbols in title (comma, hyphens, ...) also produce a bug in Cosma.

**Comment by Myllaume** [comment]
To be sure, the following titles do not cause any problem during my tests:

- `toto - tata`
- `'2001-01-01'`

**Comment by kevinpolisano** [comment]
It is not a bug raising an error, sorry I would like to say that the "link text" not in 'title' field but in the alternative syntax for links—namely [[id|link text]]—is not properly interpreted in Cosma.

![Capture d’écran 2023-01-14 à 14 18 02](https://user-images.githubusercontent.com/25388926/212474720-9dc8a856-ff32-425d-ad4a-1c0e3e80aa2b.jpg)
![Capture d’écran 2023-01-14 à 14 19 09](https://user-images.githubusercontent.com/25388926/212474723-8343ee87-e8df-491f-a274-56f232aeced3.jpg)

**Comment by infologie** [comment]
This is fixed in Cosma CLI v2-beta-2. We'll close this when the GUI v2 is released.

I have also confirmed the other issue, with the alternative syntax. I'm opening a separate issue for it.
