### ISSUE TITLE
[Enhancement] Links collapsed by default

### ISSUE THREAD

**Issue by IgnacioHeredia** [graphlab-fr/cosma#84]
### Which part of Cosma is your request about?

- [ ] command-line interface
- [X] cosmoscope (HTML file)
- [ ] documentation
- [ ] other

### Describe your request:

Hi,
I have found that links are collapsed by default.

![image](https://github.com/graphlab-fr/cosma/assets/16413205/d9b8fd42-06de-4ed8-810e-45cc9b2e06ee)

I would like to have them uncollaped, just as backlinks. I seem to remember that this was the default behaviour in old cosma, though not 100% sure right now.

Is there a way to configure this behaviour in the [user manual](https://cosma.arthurperret.fr/user-manual.html#configuration)? Because I haven't found it.

Thanks!

**Comment by infologie** [comment]
@IgnacioHeredia I did this during the last patch. You are right that the "Links" section was not collapsed before. Thank you for providing a screenshot, it's very useful because it explains why the feature is useful to you. I mostly use backlinks. I didn't realize some users would choose to write links in such a compact way and then use the Links section to display outgoing link titles. I will reverse this ASAP and think about a way to make it customizable through the configuration.

**Comment by infologie** [comment]
@IgnacioHeredia I reverted the change, you can update to the latest version (v2.1.2) from NPM.

**Comment by IgnacioHeredia** [comment]
Thanks @infologie !
